import type { Metadata } from "next";
import "./globals.css";
import {Outfit} from 'next/font/google'
const outfit = Outfit({subsets: ['latin'], weight:["400", "500", "600"]})
import Header from "@/app/components/Header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return( 

    <html lang="en">
      <body className={outfit.className} >
        
      
    <div className="container">
    
    <div className="wrapper  "> <Header/>{children}</div>
    
    </div>
    </body>
    </html>
  )
}
